name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Package Helm chart
        run: |
          helm package ./chart --destination ./packaged

      - name: Push Helm chart to GHCR
        run: |
          CHART_PACKAGE=$(ls ./packaged/*.tgz)
          helm push "$CHART_PACKAGE" oci://ghcr.io/${{ github.repository }}

